#### This script does the following:
- formats and exports  all non tdm inputs tables as csvs
- performs a basic check (coming soon...)
- creates the policy override ("zoning_parcels_p")
- loads the input tables into the h5

In [1]:
# import arcpy
# from arcpy import env
from datetime import date
import os
# from arcgis import GIS
# from arcgis.features import GeoAccessor
import pandas as pd
import numpy as np
# from zipfile import ZipFile
# import logging

# import geopandas as gpd

# arcpy.env.overwriteOutput = True
# arcpy.env.parallelProcessingFactor = "90%"

# show all columns
# pd.options.display.max_columns = None
# pd.set_option('display.max_rows', None)   # Show all rows
pd.set_option('display.max_columns', None) # Show all columns

# pd.DataFrame.spatial.from_featureclass(???)
# df.spatial.to_featureclass(location=???,sanitize_columns=False)

In [2]:
d = date.today().strftime("%Y%m%d")

In [3]:
mode = 'v900' 
# mode = 'v832' 
scenario = 'rtp'
# scenario = 'no-center'
# scenario = 'metro-urban'

In [4]:
out_folder = f'Outputs\\{mode}_Inputs_{d}'

if not os.path.exists(out_folder):
    os.makedirs(out_folder)


# gdb = os.path.join(outputs[0], outputs[1])

# if not arcpy.Exists(gdb):
#     arcpy.CreateFileGDB_management(outputs[0], outputs[1])

# Step 1) Export tables from the Geodatabase

# *parcels*

In [5]:
# # get the grid ID for utility restiction
# target_features = r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\remm_base_year_data.gdb\parcels"
# join_features = r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\utility_restriction_grid.shp"
# output_features = os.path.join(gdb, "_01_parcels_grid_sj")

# fieldmappings = arcpy.FieldMappings()
# fieldmappings.addTable(target_features)
# fieldmappings.addTable(join_features)

# # # max_dua
# # fieldindex = fieldmappings.findFieldMapIndex('max_dua')
# # fieldmap = fieldmappings.getFieldMap(fieldindex)
# # fieldmap.mergeRule = 'Mean'
# # fieldmappings.replaceFieldMap(fieldindex, fieldmap)

# # run the spatial join
# sj3 = arcpy.SpatialJoin_analysis(target_features, join_features, output_features,'JOIN_ONE_TO_ONE', "KEEP_ALL", 
#                            fieldmappings, "HAVE_THEIR_CENTER_IN")

In [6]:
# p = gpd.read_file(gdb, layer="_01_parcels_grid_sj")
# p

In [7]:
# del p['Shape_Area']
# del p['Shape_Length']
# del p['Id']
# del p['Join_Count']
# del p['TARGET_FID']
# p['parcel_id'] = p['parcel_id'].astype('Int32')
# print(p.shape)

In [8]:
# p.to_csv(os.path.join(out_folder, f"parcels_{d}.csv"), index=False)

# *buildings*

In [9]:
# b = pd.DataFrame.spatial.from_featureclass(r"..\Current_Inputs\remm_base_year.gdb\buildings")
# del b['OBJECTID']
# del b['SHAPE']

# expanded_du = pd.read_csv(r"..\Current_Inputs\expanded_DU_for_BuildingTable.csv")

# expand the residential units
# b_new = b.merge(expanded_du, on='parcel_id', how='left')
# b_new['parcel_id'] = b_new['parcel_id'].astype(int)

# subset to buildings with a building type
# b_new = b_new[(b_new['building_type_id'] >= 1)].copy()
# b_new['building_id'] = b_new['building_id'].astype(int)

# b_new.loc[b_new['addDU']> 0, 'expanded'] = 1
# b_new.loc[b_new['addDU']> 0, 'residential_units'] = b_new['residential_units'] + b_new['addDU']

# b_new = b.copy()

#b_new['pipeline_id'] = np.nan

# *zoning baseline*

In [10]:
# zb = pd.DataFrame.spatial.from_featureclass(r"..\Current_Inputs\remm_base_year.gdb\zoning_baseline")
# del zb['SHAPE']
# del zb['OBJECTID']

# zb['parcel_id'] = zb['parcel_id'].astype(int)


# zb_mag = pd.read_csv(r"..\Current_Inputs\New MAG Policy and Pipeline\zoning_baseline_MAG20230330.csv")
# zb_mag_ids = zb_mag['parcel_id'].to_list()
# zb_no_mag = zb[zb['parcel_id'].isin(zb_mag_ids) == False].copy()
# zb_new = pd.concat([zb_no_mag, zb_mag])

# # remap back to the old true/false format
# if mode == 'v832':
#     codes = {1:'t', 0:'f'}
#     zb_new['type1'] = zb_new['type1'].map(codes).astype(str)
#     zb_new['type2'] = zb_new['type2'].map(codes).astype(str)
#     zb_new['type3'] = zb_new['type3'].map(codes).astype(str)
#     zb_new['type4'] = zb_new['type4'].map(codes).astype(str)
#     zb_new['type5'] = zb_new['type5'].map(codes).astype(str)
#     zb_new['type6'] = zb_new['type6'].map(codes).astype(str)
#     zb_new['type7'] = zb_new['type7'].map(codes).astype(str)
#     zb_new['type8'] = zb_new['type8'].map(codes).astype(str)

if mode == 'v900':
    pass

# *pipeline jobs (insert into h5 later)*

In [11]:
# pj = pd.read_csv(r"..\Current_Inputs\pipelineJobs_20230405.csv")

# *pipeline buildings (insert into h5 later)*

In [12]:
# # pb = pd.read_csv(r"..\Current_Inputs\pipeline_buildings_WFRC_20230202.csv")
# # pb_mag = pd.read_csv(r"..\Current_Inputs\New MAG Policy and Pipeline\pipeline_buildings_MAG20221209.csv")
# # pb_new = pd.concat([pb, pb_mag])

# pb_new = pd.read_csv(r"..\Current_Inputs\pipeline_buildings_20230405.csv")
# del pb_new['TAZID_900']

In [13]:
# # (ZONING BASELINE) Make parcels that have pipeline building or jobs, "undevelopable"
# ids_pb = pb_new[pb_new['DEVTYPE']!='demolition']['parcel_id'].to_list()
# ids_pj = pj['building_id'].to_list()
# pipeline_ids = set(ids_pb + ids_pj)

# # step 1 set zoning baseline to no build
# zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'max_dua'] = np.nan
# zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'max_far'] = np.nan

# if mode == 'v832':
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type1'] = 'f'
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type2'] = 'f'
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type3'] = 'f'
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type4'] = 'f'
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type5'] = 'f'
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type6'] = 'f'
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type7'] = 'f'
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type8'] = 'f'

# if mode == 'v900':
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type1'] = 0
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type2'] = 0
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type3'] = 0
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type4'] = 0
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type5'] = 0
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type6'] = 0
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type7'] = 0
#     zb_new.loc[zb_new['parcel_id'].isin(pipeline_ids)==True, 'type8'] = 0

# # step 2 set parcels to no build
# p.loc[p['parcel_id'].isin(pipeline_ids)==True, 'NoBuild'] = 1

In [14]:
# # (BUILDINGS) Increase job spaces in SL and Davis County where pipeline action doesn't occur
# b_new = b_new.merge(p[['parcel_id', 'county_id']], on='parcel_id', how='left')
# b_new.loc[(b_new['county_id'] == 11) & (b_new['job_spaces'] > 0) & (b_new['building_id'].isin(pipeline_ids)==False), 'job_spaces'] = round(b_new['job_spaces'] * 1.16)
# b_new.loc[(b_new['county_id'] == 35) & (b_new['job_spaces'] > 0) & (b_new['building_id'].isin(pipeline_ids)==False), 'job_spaces'] = round(b_new['job_spaces'] * 1.085)
# del b_new['county_id']

In [15]:
# check to ensure demolition and construction dont occur in the same year on the same parcel
# remember to use redevelop code

# *zoning parcels p (AKA policy override)*

In [16]:
# # select scenario
# pop = os.path.join(r"..\Current_Inputs\policy_override.gdb\policy_override_polygons")
# pop_lyr = arcpy.MakeFeatureLayer_management(pop, 'pop_lyr')



# # optional scenarios
# if scenario == 'metro-urban':
#     query = "(AreaType IN ('Metropolitan Center', 'Urban Center', 'Employment District', 'Special District', 'Industrial District') AND \
#             AreaName NOT IN ('Porter Rockwell', 'Fore Lakes Center', 'Old Mill')) OR \
#             AreaName IN ('Herriman Annexation', 'Herriman Porter Rockwell Center', 'Jones Ranch')"
#     arcpy.SelectLayerByAttribute_management(pop_lyr, 'NEW_SELECTION', query)

# elif scenario == 'no-center':
#     query = "(AreaType IN ('Other', 'Employment District', 'Special District', 'Industrial District')) AND \
#     (AreaName NOT IN ('Porter Rockwell', 'Fore Lakes Center', 'Old Mill')) OR \
#     (AreaName IN ('Herriman Annexation', 'Herriman Porter Rockwell Center', 'Jones Ranch'))"
#     arcpy.SelectLayerByAttribute_management(pop_lyr, 'NEW_SELECTION', query)

In [17]:
# # join parcels and buildings table, then export
# p_sdf = p[['parcel_id','Tax_Exempt','NoBuild', 'TAZID_900','SHAPE']].copy()
# b_sdf = b[['parcel_id','building_type_id2']].copy()
# p_sdf.merge(b_sdf, on='parcel_id', how='left').spatial.to_featureclass(location=os.path.join(gdb, 'parcels_buildings'),sanitize_columns=False)

In [18]:
# # clean-up
# del p['SHAPE']
# del p_sdf
# del b_sdf

In [19]:
# # create parcel pts
# parcels_pts = arcpy.FeatureToPoint_management(os.path.join(gdb, 'parcels_buildings'), os.path.join(gdb, '_02_parcels_pts'), "INSIDE")
# parcels_pts_lyr = arcpy.MakeFeatureLayer_management(parcels_pts, 'parcels_pts_lyr')

# # excluded some special case parcels
# arcpy.SelectLayerByAttribute_management(parcels_pts_lyr, 'NEW_SELECTION', "(building_type_id2 in (6,9,10,13,14,16) or Tax_Exempt = 1 or NoBuild = 1) AND (parcel_id NOT IN (13670,17117,13898,13907))")
# arcpy.DeleteFeatures_management(parcels_pts_lyr)

In [20]:
# # use spatial join to summarize max dua
# target_features = parcels_pts_lyr
# join_features = pop_lyr
# output_features = os.path.join(gdb, "_00_parcels_pts_policy_sj")

# fieldmappings = arcpy.FieldMappings()
# fieldmappings.addTable(target_features)
# fieldmappings.addTable(join_features)

# # max_dua
# fieldindex = fieldmappings.findFieldMapIndex('max_dua')
# fieldmap = fieldmappings.getFieldMap(fieldindex)
# fieldmap.mergeRule = 'Mean'
# fieldmappings.replaceFieldMap(fieldindex, fieldmap)

# # run the spatial join
# sj = arcpy.SpatialJoin_analysis(target_features, join_features, output_features,'JOIN_ONE_TO_MANY', "KEEP_COMMON", 
#                            fieldmappings, "INTERSECT")

In [21]:
# parcel_pts_policy_sdf = pd.DataFrame.spatial.from_featureclass(sj[0])

# # if the year attribute is missing, use phase year from RTP
# parcel_pts_policy_sdf.loc[(parcel_pts_policy_sdf['phase_begin_year'] > 0) & (parcel_pts_policy_sdf['year'].isna()== True), 'year'] = parcel_pts_policy_sdf['phase_begin_year']
# parcel_pts_policy_sdf = parcel_pts_policy_sdf[(parcel_pts_policy_sdf['year'] > 0)]
# parcel_pts_policy_sdf = parcel_pts_policy_sdf[['parcel_id', 'TAZID_900', 'max_dua','max_far','year','type1','type2','type3','type4','type5','type6','type7','type8','locnote','mponote', 'AreaName']].copy()

In [22]:
# # Spot adjustments to big parcels within policy
# parcel_pts_policy_sdf.loc[parcel_pts_policy_sdf['parcel_id'] == 35338, 'max_far'] = .25
# parcel_pts_policy_sdf.loc[parcel_pts_policy_sdf['parcel_id'] == 57372, 'max_far'] = .25
# parcel_pts_policy_sdf.loc[parcel_pts_policy_sdf['parcel_id'] == 48385, 'max_far'] = .2

In [23]:
# export table
# d = date.today().strftime("%Y%m%d")
# zpp_out = os.path.join(outputs[0],f'zoning_parcels_p_{d}.csv')
# parcel_pts_policy_sdf.to_csv(zpp_out, index=False)
# print(f'file exported to:{zpp_out}')

In [24]:
# # BONUS: check for duplicate entrys
# duplicate = parcel_pts_policy_sdf[parcel_pts_policy_sdf.duplicated(subset=['parcel_id', 'year'], keep =False)]
# n_duplicates = duplicate.shape[0]

# print(f'There were {n_duplicates} duplicates rows in the output.')

# if n_duplicates > 0:
#     duplicate.to_csv(os.path.join(outputs[0],f'duplicates_{d}.csv'))

In [25]:
# # join to MAG's version
# zpp = parcel_pts_policy_sdf
# zpp_mag = pd.read_csv(r"..\Current_Inputs\New MAG Policy and Pipeline\zoning_parcels_p_MAG20221209.csv")
# zpp_new = pd.concat([zpp, zpp_mag])

# *agriculture*

In [26]:
# a = pd.DataFrame.spatial.from_featureclass(r"..\Current_Inputs\remm_base_year.gdb\agriculture")
# del a['SHAPE']
# a['parcel_id'] = a['parcel_id'].astype(int)

# *redev friction*

In [27]:
# rf = pd.DataFrame.spatial.from_featureclass(r"..\Current_Inputs\remm_base_year.gdb\redev_friction")
# del rf['SHAPE']
# del rf['OBJECTID']
# rf_mag = pd.read_csv(r"..\Current_Inputs\New MAG Policy and Pipeline\redev_friction_MAG20221209.csv")
# rf_mag_ids = rf_mag['parcel_id'].to_list()
# print(len(rf))
# print(len(rf_mag))

In [28]:
# rf = rf[rf['redev_friction']>0].copy()
# rf_no_mag = rf[rf['parcel_id'].isin(rf_mag_ids) == False].copy()
# rf_new = pd.concat([rf_no_mag, rf_mag])

# rf_new['parcel_id'] = rf_new['parcel_id'].astype(int)
# rf_new.shape

# *export*

In [29]:
# p.to_csv(os.path.join(outputs[0], f'parcels_{d}.csv'), index=False)
# b_new.to_csv(os.path.join(outputs[0], f'buildings_{d}.csv'), index=False)
# zb_new.to_csv(os.path.join(outputs[0], f'zoning_baseline_{d}.csv'), index=False)
# pb_new.to_csv(os.path.join(outputs[0], f'pipeline_buildings_{d}.csv'), index=False)
# zpp_new.to_csv(os.path.join(outputs[0], f'zoning_parcels_p_{d}.csv'), index=False)
# rf_new.to_csv(os.path.join(outputs[0], f'redev_friction_{d}.csv'), index=False)
# a.to_csv(os.path.join(outputs[0], f'agriculture_{d}.csv'), index=False)

# Step 2) Create H5 database

## *Create empty hdf5*

In [30]:
# store path for new hdf5
d = date.today().strftime("%Y%m%d")
hdf_name = f'remm_data_base_year_2023_{d}'
new_hdf = os.path.join(out_folder, hdf_name + '.h5')
print(new_hdf)

# if the h5 exists already delete it; it will not overwrite
if os.path.exists(new_hdf):
    try:
        new_hdf.close()
    except:
        pass
    
    os.remove(new_hdf)

# Create empty h5   
hdf = pd.HDFStore(new_hdf)

Outputs\v900_Inputs_20260209\remm_data_base_year_2023_20260209.h5

In [31]:
p =pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\h5\parcels_20260205.csv")
p.columns

C:\Users\jreynolds\AppData\Local\Temp\ipykernel_7912\1944442342.py:1: DtypeWarning: Columns (13,34,53) have mixed types. Specify dtype option on import or set low_memory=False.
  p =pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\h5\parcels_20260205.csv")

Index(['Shape_Length', 'Shape_Area', 'Join_Count', 'TARGET_FID', 'parcel_id',
       'WFRC_parcel_id', 'county_id', 'CO_NAME', 'year_built',
       'total_market_value', 'land_value', 'building_id', 'building_type_id',
       'building_type', 'building_sqft', 'non_residential_sqft',
       'residential_units', 'job_spaces', 'stories',
       'unit_price_non_residential', 'res_price_per_sqft', 'basebldg',
       'redev_friction', 'NoBuild', 'IS_OUG', 'parcel_acres', 'Tax_Exempt',
       'parent_parcel', 'volume_one_way', 'volume_two_way',
       'volume_two_way_nofwy', 'zonal_ppa', 'x', 'y', 'note', 'parcel_sqft',
       'Split', 'Split_Factor', 'MAG_parcel_id', 'max_far', 'max_dua', 'type1',
       'type2', 'type3', 'type4', 'type5', 'type6', 'type7', 'type8',
       'TAZID_900', 'distsml_id', 'distmed_id', 'distlrg_id', 'CITY_NAME',
       'stream_dist', 'streams', 'trail_dist', 'trail', 'airport_distance',
       'airport', 'fwy_exit_dist', 'fwy_exit_new', 'bus_stop_dist_new',
       'bus_stop_new', 'bus_rte_dist', 'rail_stn_dist', 'rail_stn_new',
       'raildepot_dist', 'rail_depot', 'university_dist', 'university',
       'elevation', 'agriculture', 'TAZID_910', 'grid_id'],
      dtype='object')

In [32]:
p['county_id'].value_counts()

county_id
49    308835
35    296547
11    102058
57     83894
3       9778
Name: count, dtype: int64

In [33]:
# p['building_type' ].value_counts()

## *Create Agricululture csv (this should be on the parcel in the H5, not in a separate file)*

In [34]:
a = p[p['agriculture'] > 0].copy()
a = a[['parcel_id', 'agriculture']].copy()
a.columns = ['parcel_id', 'Agriculture']
a.to_csv(os.path.join(out_folder, f'agriculture.csv'), index=False)

## *Parcel grid ID*

In [35]:
# g = p[p['grid_id'] > 0].copy()
# g = g[['parcel_id', 'grid_id']].copy()
# g.columns = ['parcel_id', 'GRIDID']
# g.to_csv(os.path.join(out_folder, f'parcelgridID.csv'), index=False)

## *Redev friction (also should be on parcel in the H5, not separate file)*

In [36]:
rf = pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\Other\Redev_Friction_RTP2027.csv")
rf = rf[['parcel_id', 'redev_fric']].copy()
rf.rename(columns={'redev_fric':'redev_friction'}, inplace=True)
rf.to_csv(os.path.join(out_folder, f'redev_friction.csv'), index=False)
rf.head()

   parcel_id  redev_friction
0       1729            12.0
1       2206            18.0
2       2229            18.0
3       2975            15.0
4       2976            15.0

## *Add parcels*

In [37]:
# parcels
parcels = p.copy()


if mode == 'v900':
       parcels['zone_id'] = parcels['TAZID_900']



parcels['parcel_sqft'] = parcels['parcel_sqft'].astype(float)
parcels['parent_parcel'] = parcels['parcel_id'].astype(int)
parcels['zonal_ppa'] = 0
parcels['volume_one_way'] = 0
parcels['volume_two_way'] = 0
parcels['volume_two_way_nofwy'] = 0
parcels['stream'] = parcels['streams']  # delete later
parcels['fwy_exit'] = parcels['fwy_exit_new']  # delete later
parcels['train_station'] = parcels['rail_stn_new']  # delete later
parcels['bus_stop'] = parcels['bus_stop_new']  # delete later
parcels['bus_stop_dist'] = parcels['bus_stop_dist_new']  # delete later

#############################
# check x and y coordinates
#############################


parcels.rename({'parcel_sqft':'shape_area'}, axis=1, inplace=True) # delete later

#############################
# add missing land value
#############################

parcels_for_assumptions = p[(p['land_value'] > 0) & (p['parcel_acres'] > 0)].copy()
parcels_for_assumptions['land_value_per_acre'] = parcels_for_assumptions['land_value'] / parcels_for_assumptions['parcel_acres']

parcels_median_lv_acre_medium_district = parcels_for_assumptions.groupby(['distmed_id'], as_index=False)[['land_value_per_acre']].median()
parcels_median_lv_acre_medium_district.columns = ['distmed_id', 'median_land_value_per_acre_MD']
parcels = parcels.merge(parcels_median_lv_acre_medium_district, on=['distmed_id'], how='left')

# Mask for invalid building_sqft 
mask = ((parcels['land_value'].isna()) |  (parcels['land_value'].isin([0, -9999]))) 

# Fill with  values for medium district
parcels.loc[mask, 'land_value'] = round(parcels['parcel_acres'] * parcels['median_land_value_per_acre_MD'])
del parcels['median_land_value_per_acre_MD']


#############################
# county id
#############################

parcels['county_id'] = parcels['county_id'].astype(int)
       
#############################
# subset and reorder columns
#############################


if mode == 'v900':
       parcels = parcels[['zone_id', 'CO_NAME', 'county_id', 'land_value',
              'x', 'y', 'parcel_acres',
              'TAZID_900', 'parent_parcel', 'elevation',
              'fwy_exit', 'airport', 'rail_depot', 'stream', 'trail', 'university',
              'shape_area', 'volume_one_way', 'volume_two_way', 'airport_distance',
              'fwy_exit_dist', 'raildepot_dist', 'university_dist', 'trail_dist',
              'stream_dist', 'train_station', 'rail_stn_dist', 'bus_rte_dist',
              'bus_stop', 'bus_stop_dist', 'volume_two_way_nofwy', 'distsml_id',
              'distmed_id', 'distlrg_id', 'zonal_ppa', 'parcel_id','grid_id']].copy()

parcels.columns

Index(['zone_id', 'CO_NAME', 'county_id', 'land_value', 'x', 'y',
       'parcel_acres', 'TAZID_900', 'parent_parcel', 'elevation', 'fwy_exit',
       'airport', 'rail_depot', 'stream', 'trail', 'university', 'shape_area',
       'volume_one_way', 'volume_two_way', 'airport_distance', 'fwy_exit_dist',
       'raildepot_dist', 'university_dist', 'trail_dist', 'stream_dist',
       'train_station', 'rail_stn_dist', 'bus_rte_dist', 'bus_stop',
       'bus_stop_dist', 'volume_two_way_nofwy', 'distsml_id', 'distmed_id',
       'distlrg_id', 'zonal_ppa', 'parcel_id', 'grid_id'],
      dtype='object')

In [38]:
parcels.to_csv(os.path.join(out_folder, f'parcels_test.csv'), index=False)

In [39]:
parcels[parcels.index.duplicated()]

Empty DataFrame
Columns: [zone_id, CO_NAME, county_id, land_value, x, y, parcel_acres, TAZID_900, parent_parcel, elevation, fwy_exit, airport, rail_depot, stream, trail, university, shape_area, volume_one_way, volume_two_way, airport_distance, fwy_exit_dist, raildepot_dist, university_dist, trail_dist, stream_dist, train_station, rail_stn_dist, bus_rte_dist, bus_stop, bus_stop_dist, volume_two_way_nofwy, distsml_id, distmed_id, distlrg_id, zonal_ppa, parcel_id, grid_id]
Index: []

In [40]:
hdf.put('parcels', parcels.set_index('parcel_id'), format='t', data_columns=True)

In [41]:
p['building_type_id' ].value_counts()

building_type_id
 1.0       551190
 0.0        66282
 2.0        63599
 9.0        41045
-9999.0     36893
 4.0        11850
 3.0        11632
 6.0         8854
 5.0         7986
 8.0         1464
 7.0          314
Name: count, dtype: int64

## *Add buildings*

In [42]:
# buildings = p[(p['building_type_id'].isin([1,2,3,4,5,6,7,8])) & ((p['year_built'] <= 2023) | (p['year_built'].isna()==True))].copy()
# buildings['building_id'] = buildings['parcel_id'] 
# buildings['building_type_id'] = buildings['building_type_id'].replace({-9999:np.nan})
# buildings['year_built'] = buildings['year_built'].replace({-9999:np.nan})
# buildings['building_type_id'].value_counts()

In [43]:
# remap building types
buildings_lu = {0:np.nan,
                1:1,
                2:2,
                3:3,
                4:4,
                5:5,
                6:6,
                7:7,
                8:8,
                9:6, 
                10:8,
                11:8,
                12:np.nan,
                13:5,
                14:np.nan,
                15:np.nan,
                16:np.nan,
                99:np.nan}


p['building_type_id'] = p['building_type_id'].map(buildings_lu)

buildings = p[(p['building_type_id'].isin([1,2,3,4,5,6,7,8]))].copy()
buildings['building_id'] = buildings['parcel_id'] 

####################################################
# Fill missing year_built values
####################################################

buildings_for_assumptions = buildings[(buildings['year_built'] > 0)].copy()

# get the median year built by small district and building type
building_median_year_small_district = buildings_for_assumptions.groupby(['distsml_id', 'building_type_id'], as_index=False)[['year_built']].median()
building_median_year_small_district.columns = ['distsml_id', 'building_type_id', 'median_year_built_SD']
building_median_year_small_district['median_year_built_SD'] = building_median_year_small_district['median_year_built_SD'].round().astype(int)

buildings = buildings.merge(building_median_year_small_district, on=['distsml_id', 'building_type_id'], how='left')
mask = buildings['year_built'].isna() | (buildings['year_built'] == 0) | (buildings['year_built'] == -9999)
buildings.loc[mask, 'year_built'] = buildings['median_year_built_SD']
del buildings['median_year_built_SD']

# make a second pass with medium district if there are still missing years
building_median_year_medium_district = buildings_for_assumptions.groupby(['distmed_id', 'building_type_id'], as_index=False)[['year_built']].median()
building_median_year_medium_district.columns = ['distmed_id', 'building_type_id', 'median_year_built_MD']
building_median_year_medium_district['median_year_built_MD'] = building_median_year_medium_district['median_year_built_MD'].round().astype(int)

buildings = buildings.merge(building_median_year_medium_district, on=['distmed_id', 'building_type_id'], how='left')
mask = buildings['year_built'].isna() | (buildings['year_built'] == 0) | (buildings['year_built'] == -9999)
buildings.loc[mask, 'year_built'] = buildings['median_year_built_MD']
del buildings['median_year_built_MD']

# make a third pass with county if there are still missing years
building_median_year_county = buildings_for_assumptions.groupby(['county_id', 'building_type_id'], as_index=False)[['year_built']].median()
building_median_year_county.columns = ['county_id', 'building_type_id', 'median_year_built_CNTY']
building_median_year_county['median_year_built_CNTY'] = building_median_year_county['median_year_built_CNTY'].round().astype(int)

buildings = buildings.merge(building_median_year_county, on=['county_id', 'building_type_id'], how='left')
mask = buildings['year_built'].isna() | (buildings['year_built'] == 0) | (buildings['year_built'] == -9999)
buildings.loc[mask, 'year_built'] = buildings['median_year_built_CNTY']
del buildings['median_year_built_CNTY']

####################################################
# Fill missing  sqft values (this needs to account for building type specifcally sf vs rest)
####################################################

buildings_for_assumptions = buildings[(buildings['building_sqft'] > 0) & (buildings['parcel_acres'] > 0)].copy()
buildings_for_assumptions['building_sqft_per_acre'] = buildings_for_assumptions['building_sqft'] / buildings_for_assumptions['parcel_acres']

building_median_sqft_acre_medium_district = buildings_for_assumptions.groupby(['distmed_id', 'building_type_id'], as_index=False)[['building_sqft_per_acre']].median()
building_median_sqft_acre_medium_district.columns = ['distmed_id', 'building_type_id', 'median_building_sqft_per_acre_MD']
buildings = buildings.merge(building_median_sqft_acre_medium_district, on=['distmed_id', 'building_type_id'], how='left')

# Mask for invalid building_sqft 
mask = ((buildings['building_sqft'].isna()) |  (buildings['building_sqft'].isin([0, -9999]))) 

# Fill with  values for medium district
buildings.loc[mask, 'building_sqft'] = round(buildings['parcel_acres'] * buildings['median_building_sqft_per_acre_MD'])
del buildings['median_building_sqft_per_acre_MD']


# second pass with large district values
building_median_sqft_acre_large_district = buildings_for_assumptions.groupby(['distlrg_id', 'building_type_id'], as_index=False)[['building_sqft_per_acre']].median()
building_median_sqft_acre_large_district.columns = ['distlrg_id', 'building_type_id', 'median_building_sqft_per_acre_LD']
buildings = buildings.merge(building_median_sqft_acre_large_district, on=['distlrg_id', 'building_type_id'], how='left')

# Mask for invalid building_sqft 
mask = ((buildings['building_sqft'].isna()) |  (buildings['building_sqft'].isin([0, -9999]))) 

# Fill with  values for medium district
buildings.loc[mask, 'building_sqft'] = round(buildings['parcel_acres'] * buildings['median_building_sqft_per_acre_LD'])
del buildings['median_building_sqft_per_acre_LD']

# third pass with county values
building_median_sqft_acre_county = buildings_for_assumptions.groupby(['county_id', 'building_type_id'], as_index=False)[['building_sqft_per_acre']].median()
building_median_sqft_acre_county.columns = ['county_id', 'building_type_id', 'median_building_sqft_per_acre_CNTY']
buildings = buildings.merge(building_median_sqft_acre_county, on=['county_id', 'building_type_id'], how='left')

# Mask for invalid building_sqft 
mask = ((buildings['building_sqft'].isna()) |  (buildings['building_sqft'].isin([0, -9999]))) 

# Fill with  values for medium district
buildings.loc[mask, 'building_sqft'] = round(buildings['parcel_acres'] * buildings['median_building_sqft_per_acre_CNTY'])
del buildings['median_building_sqft_per_acre_CNTY']

# convert to int
buildings['building_sqft'] = buildings['building_sqft'].astype(int)

#####################################
# calculate non_residential_sqft
#####################################

mask_nonres_inapplicable = ((buildings['non_residential_sqft'].isna()) | 
                            (buildings['non_residential_sqft'].isin([0, -9999]))) & \
                           (~buildings['building_type_id'].isin([1, 2]))
buildings.loc[mask_nonres_inapplicable, 'non_residential_sqft'] = buildings['building_sqft']

mask_nonres_zero = ((buildings['non_residential_sqft'].isna()) | 
                    (buildings['non_residential_sqft'].isin([0, -9999]))) & \
                   (buildings['building_type_id'].isin([1, 2]))
buildings.loc[mask_nonres_zero, 'non_residential_sqft'] = 0

#####################################
# residential_units
#####################################

buildings['residential_units'] = buildings['residential_units'].fillna(0)
buildings['residential_units'] = buildings['residential_units'].astype(int)

#####################################
# unit_price_non_residential
#####################################

buildings['unit_price_non_residential'] = 0

#####################################
# res_price_per_sqft
#####################################

buildings['res_price_per_sqft'] = 0

######################################
# stories
######################################

buildings.loc[(buildings['stories'].isna()) | (buildings['stories'].isin([0, -9999])), 'stories'] = 1

######################################
# note
#######################################

buildings['note'] = 'base'



buildings = buildings[['parcel_id', 'building_id', 'building_sqft', 'building_type_id',
       'non_residential_sqft', 'note', 'residential_units', 'stories',
       'unit_price_non_residential', 'year_built', 'res_price_per_sqft',
       'job_spaces']].copy()


buildings.columns

Index(['parcel_id', 'building_id', 'building_sqft', 'building_type_id',
       'non_residential_sqft', 'note', 'residential_units', 'stories',
       'unit_price_non_residential', 'year_built', 'res_price_per_sqft',
       'job_spaces'],
      dtype='object')

In [44]:
buildings[buildings.index.duplicated()]

Empty DataFrame
Columns: [parcel_id, building_id, building_sqft, building_type_id, non_residential_sqft, note, residential_units, stories, unit_price_non_residential, year_built, res_price_per_sqft, job_spaces]
Index: []

In [45]:
p.groupby('CO_NAME')[['job_spaces']].sum()

           job_spaces
CO_NAME
BOX ELDER           0
DAVIS          225228
SALT LAKE     1079487
UTAH           449678
WEBER          162803

In [46]:
existing_buildings = buildings[((buildings['year_built'] <= 2023) | (buildings['year_built'].isna()==True))].copy()

In [47]:
existing_buildings.to_csv('buildings.csv', index=False)
hdf.put('buildings', existing_buildings.set_index('building_id'), format='t', data_columns=True)

## *Add jobs*

In [48]:
jobs = pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\h5\jobs_20260202.csv")
jobs_for_h5 = jobs.copy()

# if mode == 'v900':
#     # del jobs_for_h5['cid']

jobs_for_h5.rename({'parcel_id':'building_id'}, axis=1, inplace=True)

# comment this out when Box Elder is ready
jobs_for_h5 = jobs_for_h5[jobs_for_h5['county_id'] != 3].copy()

jobs_for_h5.rename({'job_id':'jobs_id'}, axis=1, inplace=True)

jobs_for_h5 = jobs_for_h5[['jobs_id', 'building_id', 'sector_id','county_id']].copy()
jobs_for_h5.dtypes

jobs_id          int64
building_id      int64
sector_id        int64
county_id      float64
dtype: object

In [49]:
hdf.put('jobs', jobs_for_h5.set_index('jobs_id'), format='t', data_columns=True)

## *Add households*

In [50]:
households = pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\h5\households_20260131.csv")
hh_for_h5 = households.copy()

hh_for_h5 = hh_for_h5[['household_id', 'cars', 'household_type_id', 'persons', 'income',
       'workers', 'children', 'age_of_head', 'race_id', 'familyhh', 'block_id',
       'building_id']].copy()

# if mode == 'v900':
#     del hh_for_h5['cid']
    
hh_for_h5.columns

Index(['household_id', 'cars', 'household_type_id', 'persons', 'income',
       'workers', 'children', 'age_of_head', 'race_id', 'familyhh', 'block_id',
       'building_id'],
      dtype='object')

In [51]:
hdf.put('households', hh_for_h5, format='t', data_columns=True)

## *Add travel data*

In [52]:
# if mode == 'v832':
#     travel_data = pd.read_csv(r"..\Current_Inputs\travel_data_2015.csv")
if mode == 'v900':
    # travel_data = pd.read_csv(r"E:\Projects\REMM-Manage-Base-Year-Data\Current_Inputs\travel_data_2019.csv")
    travel_data = pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\h5\travel_data_2023.csv")
travel_data.columns

Index(['from_zone_id', 'to_zone_id', 'travel_time', 'travel_time_transit',
       'log0', 'log1', 'log2'],
      dtype='object')

In [53]:
travel_data.shape

(13169641, 7)

In [54]:
hdf.put('travel_data', travel_data.set_index(['from_zone_id', 'to_zone_id']), format='t', data_columns=True)

## *Add zoning baseline*

In [ ]:
zoning_baseline = p[['parcel_id', 'max_dua', 'max_far', 'type1', 'type2', 'type3',
       'type4', 'type5', 'type6', 'type7', 'type8', 'Tax_Exempt', 'NoBuild']].copy()

zoning_baseline['max_height'] = 999

# set zoning baseline to no build
mask = (zoning_baseline['Tax_Exempt']==1) | (zoning_baseline['NoBuild']==1)
zoning_baseline.loc[mask, 'max_dua'] = np.nan
zoning_baseline.loc[mask, 'max_far'] = np.nan
zoning_baseline.loc[mask, 'type1'] = 0
zoning_baseline.loc[mask, 'type2'] = 0
zoning_baseline.loc[mask, 'type3'] = 0
zoning_baseline.loc[mask, 'type4'] = 0
zoning_baseline.loc[mask, 'type5'] = 0
zoning_baseline.loc[mask, 'type6'] = 0
zoning_baseline.loc[mask, 'type7'] = 0
zoning_baseline.loc[mask, 'type8'] = 0

del zoning_baseline['Tax_Exempt']
del zoning_baseline['NoBuild']

zoning_baseline.loc[(zoning_baseline['max_dua'] > 1) & (zoning_baseline['max_dua'].isna()==False), 'max_dua'] = zoning_baseline['max_dua'] * .75
zoning_baseline[['parcel_id', 'max_dua']].to_csv('zbtest.csv')

zoning_baseline.columns

Index(['parcel_id', 'max_dua', 'max_far', 'type1', 'type2', 'type3', 'type4',
       'type5', 'type6', 'type7', 'type8', 'max_height'],
      dtype='object')

In [57]:
# update zoning where pipeline buildings will develop or where jobs will be created
pb = pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\Pipeline\pipeline_buildings_20260126.csv")
pj = pd.read_csv(r"E:\Tasks\REMM-Manage-Base-Year-Data-2023\Inputs\Pipeline\pipeline_jobs_20260125.csv")

pb_ids = pb['parcel_id'].to_list()
pj_ids = pj['building_id'].to_list()

pipeline_ids = set(pb_ids + pj_ids)

# set zoning baseline to no build
mask = zoning_baseline['parcel_id'].isin(pipeline_ids)==True
zoning_baseline.loc[mask, 'max_dua'] = np.nan
zoning_baseline.loc[mask, 'max_far'] = np.nan
zoning_baseline.loc[mask, 'type1'] = 0
zoning_baseline.loc[mask, 'type2'] = 0
zoning_baseline.loc[mask, 'type3'] = 0
zoning_baseline.loc[mask, 'type4'] = 0
zoning_baseline.loc[mask, 'type5'] = 0
zoning_baseline.loc[mask, 'type6'] = 0
zoning_baseline.loc[mask, 'type7'] = 0
zoning_baseline.loc[mask, 'type8'] = 0

del pb
del pj

In [58]:
zoning_baseline.loc[zoning_baseline['max_dua']==0, 'max_dua'] = np.nan
zoning_baseline.loc[zoning_baseline['max_far']==0, 'max_far'] = np.nan
hdf.put('zoning_baseline', zoning_baseline.set_index('parcel_id'), format='t', data_columns=True)

In [59]:
# close open files
hdf.close()

# Step 3) Summary and Checks

In [60]:
# b_real = buildings.merge(p, on='parcel_id', how='left')
# parcels_buildings = p.merge(buildings, on='parcel_id', how='left')
# jobs_by_cid_and_sector = jobs.groupby(['county_id','sector_id'])[['jobs_id']].count().reset_index()
# hh_with_cid = households.merge(p, left_on='building_id', right_on='parcel_id', how='left')

In [61]:
# # logging
# logfile = os.path.join(out_folder, f'REMM_Base_Year_Data_Summary_{d}.txt')
# f = open(logfile, 'w')
# f.write(f'REMM Base Year Data Summary {d}\n\n')

In [62]:
# # parcels
# f.write('--PARCELS--\n\n')
# f.write('All Counties:\n')
# f.write(f"\tNumber of Parcels: {p.shape[0]}\n")
# f.write(f"\tVacant Buildable Land: {round(parcels_buildings[parcels_buildings['building_type_id2'] == 0]['parcel_acres'].sum(), 2)}\n")
# f.write('\n')
# f.write('Weber County:\n')
# f.write(f"\tNumber of Parcels: {p[p['county_id'] == 57].shape[0]}\n")
# f.write(f"\tVacant Buildable Land: {round(parcels_buildings[(parcels_buildings['county_id'] == 57) & (parcels_buildings['building_type_id2'] == 0) ]['parcel_acres'].sum(), 2)}\n")
# f.write('\n')
# f.write('Davis County:\n')
# f.write(f"\tNumber of Parcels: {p[p['county_id'] == 11].shape[0]}\n")
# f.write(f"\tVacant Buildable Land: {round(parcels_buildings[(parcels_buildings['county_id'] == 11) & (parcels_buildings['building_type_id2'] == 0) ]['parcel_acres'].sum(), 2)}\n")
# f.write('\n')
# f.write('Salt Lake County:\n')
# f.write(f"\tNumber of Parcels: {p[p['county_id'] == 35].shape[0]}\n")
# f.write(f"\tVacant Buildable Land: {round(parcels_buildings[(parcels_buildings['county_id'] == 35) & (parcels_buildings['building_type_id2'] == 0) ]['parcel_acres'].sum(), 2)}\n")
# f.write('\n')
# f.write('Utah County:\n')
# f.write(f"\tNumber of Parcels: {p[p['county_id'] == 49].shape[0]}\n")
# f.write(f"\tVacant Buildable Land: {round(parcels_buildings[(parcels_buildings['county_id'] == 49) & (parcels_buildings['building_type_id2'] == 0) ]['parcel_acres'].sum(), 2)}\n")
# f.write('\n')

# # buildings
# f.write('--BUILDINGS--\n\n')
# f.write('All Counties:\n')
# f.write(f"\tNumber of Buildings: {b_real.shape[0]}\n")
# f.write(f"\tResidential Units: {round(b_real['residential_units'].sum())}\n")
# f.write(f"\tJob Spaces: {round(b_real['job_spaces'].sum())}\n")
# f.write('\n')
# f.write('Weber County:\n')
# f.write(f"\tNumber of Buildings: {b_real[b_real['county_id'] == 57].shape[0]}\n")
# f.write(f"\tResidential Units: {round(b_real[b_real['county_id'] == 57]['residential_units'].sum())}\n")
# f.write(f"\tJob Spaces: {round(b_real[b_real['county_id'] == 57]['job_spaces'].sum())}\n")
# f.write('\n')
# f.write('Davis County:\n')
# f.write(f"\tNumber of Buildings: {b_real[b_real['county_id'] == 11].shape[0]}\n")
# f.write(f"\tResidential Units: {round(b_real[b_real['county_id'] == 11]['residential_units'].sum())}\n")
# f.write(f"\tJob Spaces: {round(b_real[b_real['county_id'] == 11]['job_spaces'].sum())}\n")
# f.write('\n')
# f.write('Salt Lake County:\n')
# f.write(f"\tNumber of Buildings: {b_real[b_real['county_id'] == 35].shape[0]}\n")
# f.write(f"\tResidential Units: {round(b_real[b_real['county_id'] == 35]['residential_units'].sum())}\n")
# f.write(f"\tJob Spaces: {round(b_real[b_real['county_id'] == 35]['job_spaces'].sum())}\n")
# f.write('\n')
# f.write('Utah County:\n')
# f.write(f"\tNumber of Buildings: {b_real[b_real['county_id'] == 49].shape[0]}\n")
# f.write(f"\tResidential Units: {round(b_real[b_real['county_id'] == 49]['residential_units'].sum())}\n")
# f.write(f"\tJob Spaces: {round(b_real[b_real['county_id'] == 49]['job_spaces'].sum())}\n")
# f.write('\n')

# # jobs
# f.write('--JOBS--\n\n')
# f.write('All Counties:\n')
# f.write(f"\tNumber of Jobs: {jobs.shape[0]}\n")
# # f.write(f"\tNumber of Jobs (Sector 1): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 1)].values[0][2]}\n")
# # f.write(f"\tNumber of Jobs (Sector 3): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 3)].values[0][2]}\n")
# # f.write(f"\tNumber of Jobs (Sector 4): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 4)].values[0][2]}\n")
# # f.write(f"\tNumber of Jobs (Sector 5): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 5)].values[0][2]}\n")
# # f.write(f"\tNumber of Jobs (Sector 6): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 6)].values[0][2]}\n")
# # f.write(f"\tNumber of Jobs (Sector 7): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 7)].values[0][2]}\n")
# # f.write(f"\tNumber of Jobs (Sector 9): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 9)].values[0][2]}\n")
# # f.write(f"\tNumber of Jobs (Sector 10): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['sector_id'] == 10)].values[0][2]}\n")

# f.write('\n')
# f.write('Weber County:\n')
# f.write(f"\tNumber of Jobs (Sector 1): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 1)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 3): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 3)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 4): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 4)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 5): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 5)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 6): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 6)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 7): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 7)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 9): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 9)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 10): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 57) & (jobs_by_cid_and_sector['sector_id'] == 10)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Total): {jobs[jobs['cid'] == 57].shape[0]}\n")
# f.write('\n')
# f.write('Davis County:\n')
# f.write(f"\tNumber of Jobs (Sector 1): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 1)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 3): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 3)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 4): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 4)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 5): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 5)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 6): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 6)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 7): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 7)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 9): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 9)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 10): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 11) & (jobs_by_cid_and_sector['sector_id'] == 10)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Total): {jobs[jobs['cid'] == 11].shape[0]}\n")
# f.write('\n')
# f.write('Salt Lake County:\n')
# f.write(f"\tNumber of Jobs (Sector 1): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 1)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 3): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 3)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 4): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 4)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 5): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 5)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 6): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 6)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 7): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 7)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 9): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 9)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 10): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 35) & (jobs_by_cid_and_sector['sector_id'] == 10)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Total): {jobs[jobs['cid'] == 35].shape[0]}\n")
# f.write('\n')
# f.write('Utah County:\n')
# f.write(f"\tNumber of Jobs (Sector 1): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 1)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 3): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 3)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 4): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 4)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 5): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 5)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 6): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 6)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 7): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 7)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 9): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 9)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Sector 10): {jobs_by_cid_and_sector[(jobs_by_cid_and_sector['cid'] == 49) & (jobs_by_cid_and_sector['sector_id'] == 10)].values[0][2]}\n")
# f.write(f"\tNumber of Jobs (Total): {jobs[jobs['cid'] == 49].shape[0]}\n")
# f.write('\n')

# # households
# f.write('--HOUSEHOLDS--\n\n')
# f.write('All Counties:\n')
# f.write(f"\tNumber of Households: {hh_with_cid.shape[0]}\n")
# f.write('\n')
# f.write('Weber County:\n')
# f.write(f"\tNumber of Households: {hh_with_cid[hh_with_cid['county_id'] == 57].shape[0]}\n")
# f.write('\n')
# f.write('Davis County:\n')
# f.write(f"\tNumber of Households: {hh_with_cid[hh_with_cid['county_id'] == 11].shape[0]}\n")
# f.write('\n')
# f.write('Salt Lake County:\n')
# f.write(f"\tNumber of Households: {hh_with_cid[hh_with_cid['county_id'] == 35].shape[0]}\n")
# f.write('\n')
# f.write('Utah County:\n')
# f.write(f"\tNumber of Households: {hh_with_cid[hh_with_cid['county_id'] == 49].shape[0]}\n")
# f.write('\n\n')

In [63]:
# ids_p_from_pb = pb_new['parcel_id'].to_list()
# ids_p_from_p = p['parcel_id'].to_list()
# ids_p_from_b = b['parcel_id'].to_list()
# ids_b_from_b = b_new['building_id'].to_list()
# ids_b_from_hh = households['building_id'].to_list()
# ids_b_from_j = jobs['building_id'].to_list()
# ids_zb = zb_new['parcel_id'].to_list()
# ids_rf = rf_new['parcel_id'].to_list()
# ids_a = a['parcel_id'].to_list()

In [64]:
# # ensure no index ids for any table are duplicated
# f.write('--CHECK FOR DUPLICATES--\n\n')

# if len(ids_p_from_p) == len(set(ids_p_from_p)):
#     f.write('No duplicate parcel ids in parcels\n')
#     print('No duplicates ids in parcels')

# if len(ids_b_from_b) == len(set(ids_b_from_b)):
#     f.write('No duplicate building ids in buildings\n')
#     print('No duplicates ids in buildings')

# if len(ids_zb) == len(set(ids_zb)):
#     f.write('No duplicates parcel ids in zoning baseline\n')
#     print('No duplicates ids in zoning baseline')

# if len(ids_rf) == len(set(ids_rf)):
#     f.write('No duplicate parcel ids in redev friction\n\n')
#     print('No duplicates ids in redev friction')

In [65]:
# make sure there are not external taz ids in parcel file (coming soon...)

In [66]:
# # ensure all child tables id is present in their parent table

# # ensure there is zb for every p
# p_ids_in_zb_missing_from_parcels = list(set(ids_zb) - set(ids_p_from_p))
# if len(p_ids_in_zb_missing_from_parcels) > 0:
#     print('p_ids_in_zb_missing_from_parcels')
#     print(p_ids_in_zb_missing_from_parcels)

# p_ids_in_parcels_missing_from_zb = list(set(ids_p_from_p) - set(ids_zb))
# if len(p_ids_in_parcels_missing_from_zb) > 0:
#     print('p_ids_in_parcels_missing_from_zb')
#     print(p_ids_in_parcels_missing_from_zb)

# # ensure all b pids are in p
# b_ids_in_buildings_missing_from_parcels = list(set(ids_p_from_b) - set(ids_p_from_p))
# if len(b_ids_in_buildings_missing_from_parcels) > 0:
#     print('b_ids_in_buildings_missing_from_parcels')
#     print(b_ids_in_buildings_missing_from_parcels)

# p_ids_in_parcels_missing_from_buildings = list(set(ids_p_from_p) - set(ids_p_from_b))
# if len(p_ids_in_parcels_missing_from_buildings) > 0:
#     print('p_ids_in_parcels_missing_from_buildings')
#     print(p_ids_in_parcels_missing_from_buildings)

# # ensure all rf pids are in p
# p_ids_in_rf_missing_from_parcels = list(set(ids_rf) - set(ids_p_from_p))
# if len(p_ids_in_rf_missing_from_parcels) > 0:
#     print('p_ids_in_rf_missing_from_parcels')
#     print(p_ids_in_rf_missing_from_parcels)

# # ensure all agriculture pids are in p
# p_ids_in_a_missing_from_parcels = list(set(ids_a) - set(ids_p_from_p))
# if len(p_ids_in_a_missing_from_parcels) > 0:
#     print('p_ids_in_a_missing_from_parcels')
#     print(p_ids_in_a_missing_from_parcels)

# # ensure all jobs bids are in b
# b_ids_in_jobs_missing_from_buildings = list(set(ids_b_from_j) - set(ids_b_from_b))
# if len(b_ids_in_jobs_missing_from_buildings) > 0:
#     print('b_ids_in_jobs_missing_from_buildings')
#     print(b_ids_in_jobs_missing_from_buildings)

# # ensure all households bids are in b
# b_ids_in_hh_missing_from_buildings = list(set(ids_b_from_hh) - set(ids_b_from_b))
# if len(b_ids_in_hh_missing_from_buildings) > 0:
#     print('b_ids_in_hh_missing_from_buildings')
#     print(b_ids_in_hh_missing_from_buildings)

# # ensure all pipeline buildings pids are in p
# p_ids_in_pb_missing_from_parcels = list(set(ids_p_from_pb) - set(ids_p_from_p))
# if len(p_ids_in_pb_missing_from_parcels) > 0:
#     print('p_ids_in_pb_missing_from_parcels')
#     print(p_ids_in_pb_missing_from_parcels)

# # Summarize missing data in parcels and buildings
# # Make sure max dua values make sense with building types allowed!!!!
# # Example type 1 only allowed, max dua should be between .5 and 1
# # Make sure max fars make sense with building types allowed!!!!
# # ensure jobs count per building does not exceed job spaces
# # add county controls and comparison
# # ensure county id/cid from parcel/buildings, hh and jobs table all match

In [67]:
# f.close()